#!/usr/bin/env python
this_year = 2013

name = raw_input("please input your name:")
#age = raw_input("how old are you?")
#age = input("how old are you?")
age = int(raw_input("how old are you?"))

print "hello",name,'\n'
print "you are",age,'years old!'
print "so you were born in: ",this_year - age
